package Box2D::b2Vec2;

use warnings;
use strict;
use Box2D;

use overload
	'+'      => '_add',
	'-'      => '_subtract',
	'*'      => '_multiply',
	'=='     => '_equal',
	'!='     => sub { !&_equal }, # no, this isn't autogenerated
	'.'      => '_dot',
	'x'      => '_cross',
	'abs'    => '_abs',
	'neg'    => sub { $_[0]->_negate() },
	fallback => 1,
;

sub _add {
	my ( $self, $other ) = @_;

	return Box2D::_vec2_add( $self, $other );
}

sub _subtract {
	my ( $self, $other, $swap ) = @_;

	if ($swap) {
		return Box2D::_vec2_subtract( $other, $self );
	}
	else {
		return Box2D::_vec2_subtract( $self, $other );
	}
}

# Multiplication is defined between a vector and scalar. Multiplying two
# vectors is ambiguous because either cross product or dot product may
# be intended. Use b2CrossV2V2 or b2DotV2V2 for those operations.
sub _multiply {
	my ( $self, $other ) = @_;

	return Box2D::_vec2_multiply( $other, $self );
}

sub _equal {
	my ( $self, $other ) = @_;

	return Box2D::_vec2_equal( $self, $other );
}

sub _dot {
	my ( $self, $other ) = @_;

	return Box2D::b2Dot( $self, $other );
}

sub _cross {
	my ( $self, $other, $swap ) = @_;

	if ($swap) {
		return Box2D::b2Cross( $other, $self );
	}
	else {
		return Box2D::b2Cross( $self, $other );
	}
}

sub _abs {
	my ( $self ) = @_;

	return Box2D::b2Abs( $self );
}

1;
